# Generated by Django 5.1.4 on 2025-06-04 10:30

import django.core.validators
import django.db.models.deletion
import dnb_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('yymm', models.IntegerField(default=dnb_app.models.get_default_yymm)),
                ('emp_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('doj', models.DateField()),
                ('dos', models.DateField(blank=True, null=True)),
                ('emp_status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('stipend_rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('daily_rate', models.IntegerField(blank=True, null=True)),
                ('sex_code', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('bank_cd', models.CharField(blank=True, max_length=3)),
                ('bank_acno', models.CharField(blank=True, max_length=17)),
                ('pan', models.CharField(blank=True, max_length=10)),
                ('catg', models.IntegerField(choices=[(1, 'DNB Junior'), (2, 'DNB Senior'), (3, 'Contract'), (4, 'CSR')])),
                ('catg_desc', models.CharField(max_length=50)),
                ('speciality', models.CharField(blank=True, max_length=20)),
                ('trg_duration', models.IntegerField(default=0)),
                ('stop_pay_ind', models.IntegerField(default=0)),
                ('tuition_fee_ind', models.IntegerField(default=0)),
                ('dnb_type', models.CharField(blank=True, max_length=5)),
                ('role', models.CharField(choices=[('MAST', 'Admin (MAST)'), ('FIN', 'Finance (FIN)'), ('ATT', 'Attendance (ATT)'), ('EMP', 'Employee (EMP)')], default='EMP', max_length=4)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dnbmast',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_no', models.CharField(max_length=10, unique=True)),
                ('created_by', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dnb_app.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yymm', models.IntegerField()),
                ('duty', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('al', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('cl', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('abs', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('pl', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('ml', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnb_app.employee')),
            ],
            options={
                'db_table': 'dnbatt',
                'unique_together': {('yymm', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='PayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yymm', models.IntegerField()),
                ('stipend', models.IntegerField(default=0)),
                ('adj', models.IntegerField(default=0)),
                ('itaxrec', models.IntegerField(default=0)),
                ('cessrec', models.IntegerField(default=0)),
                ('cessaddl', models.IntegerField(default=0)),
                ('gpay', models.IntegerField(default=0)),
                ('npay', models.IntegerField(default=0)),
                ('higher_tax_ind', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnb_app.employee')),
            ],
            options={
                'db_table': 'dnbpbill',
                'unique_together': {('yymm', 'employee')},
            },
        ),
    ]
