# Generated by Django 5.1.4 on 2025-06-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnb_app', '0002_alter_employee_bank_cd'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
