# Generated by Django 5.1.4 on 2025-06-07 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnb_app', '0003_employee_is_online_employee_last_login_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('can_manage_users', 'Can create/update users'), ('can_approve_payments', 'Can approve financial transactions'), ('view_audit_logs', 'Can view system audit logs')]},
        ),
        migrations.AddField(
            model_name='employee',
            name='is_approver',
            field=models.BooleanField(default=False, help_text='Can approve financial transactions'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_auditor',
            field=models.BooleanField(default=False, help_text='Can view audit logs'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('SUPER', 'Super Admin'), ('DEPT_ADMIN', 'Department Admin'), ('FIN', 'Finance Manager'), ('HR', 'HR Manager'), ('EMP', 'Employee')], default='EMP', help_text='Determines system access level', max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dnb_app.department'),
        ),
    ]
