# Generated by Django 5.1.4 on 2025-06-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnb_app', '0005_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(choices=[('SUPER', 'Superuser'), ('ADMIN', 'Admin'), ('FIN', 'Finance'), ('HR', 'HR'), ('EMP', 'Employee')], default='EMP', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('SUPER', 'Superuser'), ('ADMIN', 'Admin'), ('FIN', 'Finance'), ('HR', 'HR'), ('EMP', 'Employee')], default='EMP', help_text='Determines system access level', max_length=15),
        ),
    ]
