# Generated by Django 5.1.4 on 2025-06-09 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnb_app', '0006_alter_employee_phone_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact number with country code', max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('SUPER', 'Superuser'), ('ADMIN', 'Admin'), ('FIN', 'Finance Manager'), ('HR', 'HR Manager'), ('EMP', 'Employee')], default='EMP', help_text='Determines system access level', max_length=15),
        ),
    ]
