# Generated by Django 5.1.4 on 2025-06-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnb_app', '0010_alter_employee_role_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('SUPER', 'Superuser'), ('ADMIN', 'Admin'), ('FIN', 'Finance Manager'), ('ATT', 'HR Manager')], default='HR', help_text='System access level', max_length=15),
        ),
    ]
