# Generated by Django 5.1.4 on 2025-06-11 00:01

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('dnb_app', '0011_alter_employee_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_approver',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_auditor',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_login_time',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_logout_time',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
