# Generated by Django 5.2.1 on 2025-06-13 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnb_app', '0012_remove_employee_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='catg',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='catg_desc',
            field=models.CharField(choices=[('DNB', 'DNB'), ('CONTRACTUAL', 'CONTRACTUAL'), ('CSR', 'CSR')], max_length=50),
        ),
    ]
